version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ci_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - redis
      - mailpit
    networks:
      - ci4-network

  nginx:
    image: nginx:latest
    container_name: ci_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - ci4-network

  db:
    image: mysql:8.0
    container_name: ci_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ci_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ci4-network

  redis:
    image: redis:latest
    container_name: ci_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ci4-network

  mailpit:
    image: axllent/mailpit
    container_name: ci_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_RELAY_HOST: "smtp.gmail.com"
      MP_RELAY_PORT: "587"
      MP_RELAY_USERNAME: "aleshkacygankov@gmail.com"
      MP_RELAY_PASSWORD: "cla2208alex20azs"
      MP_RELAY_TLS: "true"
    volumes:
      - mailpit_data:/data
    networks:
      - ci4-network

volumes:
  mysql_data:
  redis_data:
  mailpit_data:

networks:
  ci4-network:
    driver: bridge
