version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ci_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - redis
    networks:
      - ci4-network

  nginx:
    image: nginx:latest
    container_name: ci_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - ci4-network

  db:
    image: mysql:8.0
    container_name: ci_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ci_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ci4-network

  redis:
    image: redis:latest
    container_name: ci_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ci4-network

volumes:
  mysql_data:
  redis_data:

networks:
  ci4-network:
    driver: bridge
