version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ci_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - db
      - redis
      - mailhog
    networks:
      - ci4-network
    environment:
      - MAIL_HOST=mailhog
      - SWOOLE_HOST=${SWOOLE_HOST:-0.0.0.0}
      - SWOOLE_PORT=${SWOOLE_PORT:-9501}
    ports:
      - "${SWOOLE_PORT:-9501}:${SWOOLE_PORT:-9501}"
      - "9502:9502"

  nginx:
    image: nginx:latest
    container_name: ci_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - ci4-network

  db:
    image: mysql:8.0
    container_name: ci_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ci_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ci4-network

  redis:
    image: redis:latest
    container_name: ci_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ci4-network

  mailhog:
    image: mailhog/mailhog
    container_name: ci_mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailhog_data:/home/mailhog
    networks:
      - ci4-network

volumes:
  mysql_data:
  redis_data:
  mailhog_data:

networks:
  ci4-network:
    driver: bridge
